/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ClientsIndexRouteImport } from './routes/clients/index'
import { Route as ClientsCreateRouteImport } from './routes/clients/create'
import { Route as ClientLocationsRouteImport } from './routes/client/locations'
import { Route as ClientDetailsRouteImport } from './routes/client/details'
import { Route as ClientDashboardRouteImport } from './routes/client/dashboard'
import { Route as ClientAssetsRouteImport } from './routes/client/assets'
import { Route as ClientAssetGroupsRouteImport } from './routes/client/asset-groups'
import { Route as ClientUsersIndexRouteImport } from './routes/client/users/index'
import { Route as ClientRolesIndexRouteImport } from './routes/client/roles/index'
import { Route as ClientGroupsIndexRouteImport } from './routes/client/groups/index'
import { Route as ClientUsersCreateRouteImport } from './routes/client/users/create'
import { Route as ClientUsersUserIdRouteImport } from './routes/client/users/$userId'
import { Route as ClientRolesCreateRouteImport } from './routes/client/roles/create'
import { Route as ClientRolesRoleIdRouteImport } from './routes/client/roles/$roleId'
import { Route as ClientLocationsCreateRouteImport } from './routes/client/locations/create'
import { Route as ClientLocationsLocationIdRouteImport } from './routes/client/locations/$locationId'
import { Route as ClientGroupsCreateRouteImport } from './routes/client/groups/create'
import { Route as ClientGroupsGroupIdRouteImport } from './routes/client/groups/$groupId'
import { Route as ClientAssetsCreateRouteImport } from './routes/client/assets/create'
import { Route as ClientAssetsAssetIdRouteImport } from './routes/client/assets/$assetId'
import { Route as ClientAssetGroupsGroupIdRouteImport } from './routes/client/asset-groups/$groupId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsIndexRoute = ClientsIndexRouteImport.update({
  id: '/clients/',
  path: '/clients/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsCreateRoute = ClientsCreateRouteImport.update({
  id: '/clients/create',
  path: '/clients/create',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientLocationsRoute = ClientLocationsRouteImport.update({
  id: '/client/locations',
  path: '/client/locations',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientDetailsRoute = ClientDetailsRouteImport.update({
  id: '/client/details',
  path: '/client/details',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientDashboardRoute = ClientDashboardRouteImport.update({
  id: '/client/dashboard',
  path: '/client/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientAssetsRoute = ClientAssetsRouteImport.update({
  id: '/client/assets',
  path: '/client/assets',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientAssetGroupsRoute = ClientAssetGroupsRouteImport.update({
  id: '/client/asset-groups',
  path: '/client/asset-groups',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientUsersIndexRoute = ClientUsersIndexRouteImport.update({
  id: '/client/users/',
  path: '/client/users/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientRolesIndexRoute = ClientRolesIndexRouteImport.update({
  id: '/client/roles/',
  path: '/client/roles/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientGroupsIndexRoute = ClientGroupsIndexRouteImport.update({
  id: '/client/groups/',
  path: '/client/groups/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientUsersCreateRoute = ClientUsersCreateRouteImport.update({
  id: '/client/users/create',
  path: '/client/users/create',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientUsersUserIdRoute = ClientUsersUserIdRouteImport.update({
  id: '/client/users/$userId',
  path: '/client/users/$userId',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientRolesCreateRoute = ClientRolesCreateRouteImport.update({
  id: '/client/roles/create',
  path: '/client/roles/create',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientRolesRoleIdRoute = ClientRolesRoleIdRouteImport.update({
  id: '/client/roles/$roleId',
  path: '/client/roles/$roleId',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientLocationsCreateRoute = ClientLocationsCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => ClientLocationsRoute,
} as any)
const ClientLocationsLocationIdRoute =
  ClientLocationsLocationIdRouteImport.update({
    id: '/$locationId',
    path: '/$locationId',
    getParentRoute: () => ClientLocationsRoute,
  } as any)
const ClientGroupsCreateRoute = ClientGroupsCreateRouteImport.update({
  id: '/client/groups/create',
  path: '/client/groups/create',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientGroupsGroupIdRoute = ClientGroupsGroupIdRouteImport.update({
  id: '/client/groups/$groupId',
  path: '/client/groups/$groupId',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientAssetsCreateRoute = ClientAssetsCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => ClientAssetsRoute,
} as any)
const ClientAssetsAssetIdRoute = ClientAssetsAssetIdRouteImport.update({
  id: '/$assetId',
  path: '/$assetId',
  getParentRoute: () => ClientAssetsRoute,
} as any)
const ClientAssetGroupsGroupIdRoute =
  ClientAssetGroupsGroupIdRouteImport.update({
    id: '/$groupId',
    path: '/$groupId',
    getParentRoute: () => ClientAssetGroupsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/client/asset-groups': typeof ClientAssetGroupsRouteWithChildren
  '/client/assets': typeof ClientAssetsRouteWithChildren
  '/client/dashboard': typeof ClientDashboardRoute
  '/client/details': typeof ClientDetailsRoute
  '/client/locations': typeof ClientLocationsRouteWithChildren
  '/clients/create': typeof ClientsCreateRoute
  '/clients': typeof ClientsIndexRoute
  '/client/asset-groups/$groupId': typeof ClientAssetGroupsGroupIdRoute
  '/client/assets/$assetId': typeof ClientAssetsAssetIdRoute
  '/client/assets/create': typeof ClientAssetsCreateRoute
  '/client/groups/$groupId': typeof ClientGroupsGroupIdRoute
  '/client/groups/create': typeof ClientGroupsCreateRoute
  '/client/locations/$locationId': typeof ClientLocationsLocationIdRoute
  '/client/locations/create': typeof ClientLocationsCreateRoute
  '/client/roles/$roleId': typeof ClientRolesRoleIdRoute
  '/client/roles/create': typeof ClientRolesCreateRoute
  '/client/users/$userId': typeof ClientUsersUserIdRoute
  '/client/users/create': typeof ClientUsersCreateRoute
  '/client/groups': typeof ClientGroupsIndexRoute
  '/client/roles': typeof ClientRolesIndexRoute
  '/client/users': typeof ClientUsersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/client/asset-groups': typeof ClientAssetGroupsRouteWithChildren
  '/client/assets': typeof ClientAssetsRouteWithChildren
  '/client/dashboard': typeof ClientDashboardRoute
  '/client/details': typeof ClientDetailsRoute
  '/client/locations': typeof ClientLocationsRouteWithChildren
  '/clients/create': typeof ClientsCreateRoute
  '/clients': typeof ClientsIndexRoute
  '/client/asset-groups/$groupId': typeof ClientAssetGroupsGroupIdRoute
  '/client/assets/$assetId': typeof ClientAssetsAssetIdRoute
  '/client/assets/create': typeof ClientAssetsCreateRoute
  '/client/groups/$groupId': typeof ClientGroupsGroupIdRoute
  '/client/groups/create': typeof ClientGroupsCreateRoute
  '/client/locations/$locationId': typeof ClientLocationsLocationIdRoute
  '/client/locations/create': typeof ClientLocationsCreateRoute
  '/client/roles/$roleId': typeof ClientRolesRoleIdRoute
  '/client/roles/create': typeof ClientRolesCreateRoute
  '/client/users/$userId': typeof ClientUsersUserIdRoute
  '/client/users/create': typeof ClientUsersCreateRoute
  '/client/groups': typeof ClientGroupsIndexRoute
  '/client/roles': typeof ClientRolesIndexRoute
  '/client/users': typeof ClientUsersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/client/asset-groups': typeof ClientAssetGroupsRouteWithChildren
  '/client/assets': typeof ClientAssetsRouteWithChildren
  '/client/dashboard': typeof ClientDashboardRoute
  '/client/details': typeof ClientDetailsRoute
  '/client/locations': typeof ClientLocationsRouteWithChildren
  '/clients/create': typeof ClientsCreateRoute
  '/clients/': typeof ClientsIndexRoute
  '/client/asset-groups/$groupId': typeof ClientAssetGroupsGroupIdRoute
  '/client/assets/$assetId': typeof ClientAssetsAssetIdRoute
  '/client/assets/create': typeof ClientAssetsCreateRoute
  '/client/groups/$groupId': typeof ClientGroupsGroupIdRoute
  '/client/groups/create': typeof ClientGroupsCreateRoute
  '/client/locations/$locationId': typeof ClientLocationsLocationIdRoute
  '/client/locations/create': typeof ClientLocationsCreateRoute
  '/client/roles/$roleId': typeof ClientRolesRoleIdRoute
  '/client/roles/create': typeof ClientRolesCreateRoute
  '/client/users/$userId': typeof ClientUsersUserIdRoute
  '/client/users/create': typeof ClientUsersCreateRoute
  '/client/groups/': typeof ClientGroupsIndexRoute
  '/client/roles/': typeof ClientRolesIndexRoute
  '/client/users/': typeof ClientUsersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/client/asset-groups'
    | '/client/assets'
    | '/client/dashboard'
    | '/client/details'
    | '/client/locations'
    | '/clients/create'
    | '/clients'
    | '/client/asset-groups/$groupId'
    | '/client/assets/$assetId'
    | '/client/assets/create'
    | '/client/groups/$groupId'
    | '/client/groups/create'
    | '/client/locations/$locationId'
    | '/client/locations/create'
    | '/client/roles/$roleId'
    | '/client/roles/create'
    | '/client/users/$userId'
    | '/client/users/create'
    | '/client/groups'
    | '/client/roles'
    | '/client/users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/client/asset-groups'
    | '/client/assets'
    | '/client/dashboard'
    | '/client/details'
    | '/client/locations'
    | '/clients/create'
    | '/clients'
    | '/client/asset-groups/$groupId'
    | '/client/assets/$assetId'
    | '/client/assets/create'
    | '/client/groups/$groupId'
    | '/client/groups/create'
    | '/client/locations/$locationId'
    | '/client/locations/create'
    | '/client/roles/$roleId'
    | '/client/roles/create'
    | '/client/users/$userId'
    | '/client/users/create'
    | '/client/groups'
    | '/client/roles'
    | '/client/users'
  id:
    | '__root__'
    | '/'
    | '/client/asset-groups'
    | '/client/assets'
    | '/client/dashboard'
    | '/client/details'
    | '/client/locations'
    | '/clients/create'
    | '/clients/'
    | '/client/asset-groups/$groupId'
    | '/client/assets/$assetId'
    | '/client/assets/create'
    | '/client/groups/$groupId'
    | '/client/groups/create'
    | '/client/locations/$locationId'
    | '/client/locations/create'
    | '/client/roles/$roleId'
    | '/client/roles/create'
    | '/client/users/$userId'
    | '/client/users/create'
    | '/client/groups/'
    | '/client/roles/'
    | '/client/users/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ClientAssetGroupsRoute: typeof ClientAssetGroupsRouteWithChildren
  ClientAssetsRoute: typeof ClientAssetsRouteWithChildren
  ClientDashboardRoute: typeof ClientDashboardRoute
  ClientDetailsRoute: typeof ClientDetailsRoute
  ClientLocationsRoute: typeof ClientLocationsRouteWithChildren
  ClientsCreateRoute: typeof ClientsCreateRoute
  ClientsIndexRoute: typeof ClientsIndexRoute
  ClientGroupsGroupIdRoute: typeof ClientGroupsGroupIdRoute
  ClientGroupsCreateRoute: typeof ClientGroupsCreateRoute
  ClientRolesRoleIdRoute: typeof ClientRolesRoleIdRoute
  ClientRolesCreateRoute: typeof ClientRolesCreateRoute
  ClientUsersUserIdRoute: typeof ClientUsersUserIdRoute
  ClientUsersCreateRoute: typeof ClientUsersCreateRoute
  ClientGroupsIndexRoute: typeof ClientGroupsIndexRoute
  ClientRolesIndexRoute: typeof ClientRolesIndexRoute
  ClientUsersIndexRoute: typeof ClientUsersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients/': {
      id: '/clients/'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof ClientsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients/create': {
      id: '/clients/create'
      path: '/clients/create'
      fullPath: '/clients/create'
      preLoaderRoute: typeof ClientsCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client/locations': {
      id: '/client/locations'
      path: '/client/locations'
      fullPath: '/client/locations'
      preLoaderRoute: typeof ClientLocationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client/details': {
      id: '/client/details'
      path: '/client/details'
      fullPath: '/client/details'
      preLoaderRoute: typeof ClientDetailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client/dashboard': {
      id: '/client/dashboard'
      path: '/client/dashboard'
      fullPath: '/client/dashboard'
      preLoaderRoute: typeof ClientDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client/assets': {
      id: '/client/assets'
      path: '/client/assets'
      fullPath: '/client/assets'
      preLoaderRoute: typeof ClientAssetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client/asset-groups': {
      id: '/client/asset-groups'
      path: '/client/asset-groups'
      fullPath: '/client/asset-groups'
      preLoaderRoute: typeof ClientAssetGroupsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client/users/': {
      id: '/client/users/'
      path: '/client/users'
      fullPath: '/client/users'
      preLoaderRoute: typeof ClientUsersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client/roles/': {
      id: '/client/roles/'
      path: '/client/roles'
      fullPath: '/client/roles'
      preLoaderRoute: typeof ClientRolesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client/groups/': {
      id: '/client/groups/'
      path: '/client/groups'
      fullPath: '/client/groups'
      preLoaderRoute: typeof ClientGroupsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client/users/create': {
      id: '/client/users/create'
      path: '/client/users/create'
      fullPath: '/client/users/create'
      preLoaderRoute: typeof ClientUsersCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client/users/$userId': {
      id: '/client/users/$userId'
      path: '/client/users/$userId'
      fullPath: '/client/users/$userId'
      preLoaderRoute: typeof ClientUsersUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client/roles/create': {
      id: '/client/roles/create'
      path: '/client/roles/create'
      fullPath: '/client/roles/create'
      preLoaderRoute: typeof ClientRolesCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client/roles/$roleId': {
      id: '/client/roles/$roleId'
      path: '/client/roles/$roleId'
      fullPath: '/client/roles/$roleId'
      preLoaderRoute: typeof ClientRolesRoleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client/locations/create': {
      id: '/client/locations/create'
      path: '/create'
      fullPath: '/client/locations/create'
      preLoaderRoute: typeof ClientLocationsCreateRouteImport
      parentRoute: typeof ClientLocationsRoute
    }
    '/client/locations/$locationId': {
      id: '/client/locations/$locationId'
      path: '/$locationId'
      fullPath: '/client/locations/$locationId'
      preLoaderRoute: typeof ClientLocationsLocationIdRouteImport
      parentRoute: typeof ClientLocationsRoute
    }
    '/client/groups/create': {
      id: '/client/groups/create'
      path: '/client/groups/create'
      fullPath: '/client/groups/create'
      preLoaderRoute: typeof ClientGroupsCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client/groups/$groupId': {
      id: '/client/groups/$groupId'
      path: '/client/groups/$groupId'
      fullPath: '/client/groups/$groupId'
      preLoaderRoute: typeof ClientGroupsGroupIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client/assets/create': {
      id: '/client/assets/create'
      path: '/create'
      fullPath: '/client/assets/create'
      preLoaderRoute: typeof ClientAssetsCreateRouteImport
      parentRoute: typeof ClientAssetsRoute
    }
    '/client/assets/$assetId': {
      id: '/client/assets/$assetId'
      path: '/$assetId'
      fullPath: '/client/assets/$assetId'
      preLoaderRoute: typeof ClientAssetsAssetIdRouteImport
      parentRoute: typeof ClientAssetsRoute
    }
    '/client/asset-groups/$groupId': {
      id: '/client/asset-groups/$groupId'
      path: '/$groupId'
      fullPath: '/client/asset-groups/$groupId'
      preLoaderRoute: typeof ClientAssetGroupsGroupIdRouteImport
      parentRoute: typeof ClientAssetGroupsRoute
    }
  }
}

interface ClientAssetGroupsRouteChildren {
  ClientAssetGroupsGroupIdRoute: typeof ClientAssetGroupsGroupIdRoute
}

const ClientAssetGroupsRouteChildren: ClientAssetGroupsRouteChildren = {
  ClientAssetGroupsGroupIdRoute: ClientAssetGroupsGroupIdRoute,
}

const ClientAssetGroupsRouteWithChildren =
  ClientAssetGroupsRoute._addFileChildren(ClientAssetGroupsRouteChildren)

interface ClientAssetsRouteChildren {
  ClientAssetsAssetIdRoute: typeof ClientAssetsAssetIdRoute
  ClientAssetsCreateRoute: typeof ClientAssetsCreateRoute
}

const ClientAssetsRouteChildren: ClientAssetsRouteChildren = {
  ClientAssetsAssetIdRoute: ClientAssetsAssetIdRoute,
  ClientAssetsCreateRoute: ClientAssetsCreateRoute,
}

const ClientAssetsRouteWithChildren = ClientAssetsRoute._addFileChildren(
  ClientAssetsRouteChildren,
)

interface ClientLocationsRouteChildren {
  ClientLocationsLocationIdRoute: typeof ClientLocationsLocationIdRoute
  ClientLocationsCreateRoute: typeof ClientLocationsCreateRoute
}

const ClientLocationsRouteChildren: ClientLocationsRouteChildren = {
  ClientLocationsLocationIdRoute: ClientLocationsLocationIdRoute,
  ClientLocationsCreateRoute: ClientLocationsCreateRoute,
}

const ClientLocationsRouteWithChildren = ClientLocationsRoute._addFileChildren(
  ClientLocationsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ClientAssetGroupsRoute: ClientAssetGroupsRouteWithChildren,
  ClientAssetsRoute: ClientAssetsRouteWithChildren,
  ClientDashboardRoute: ClientDashboardRoute,
  ClientDetailsRoute: ClientDetailsRoute,
  ClientLocationsRoute: ClientLocationsRouteWithChildren,
  ClientsCreateRoute: ClientsCreateRoute,
  ClientsIndexRoute: ClientsIndexRoute,
  ClientGroupsGroupIdRoute: ClientGroupsGroupIdRoute,
  ClientGroupsCreateRoute: ClientGroupsCreateRoute,
  ClientRolesRoleIdRoute: ClientRolesRoleIdRoute,
  ClientRolesCreateRoute: ClientRolesCreateRoute,
  ClientUsersUserIdRoute: ClientUsersUserIdRoute,
  ClientUsersCreateRoute: ClientUsersCreateRoute,
  ClientGroupsIndexRoute: ClientGroupsIndexRoute,
  ClientRolesIndexRoute: ClientRolesIndexRoute,
  ClientUsersIndexRoute: ClientUsersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
